#page title
page_title                                : CruisePortIQ - Cruise Port Guide App for Things to Do, Transport & Offline Maps                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6751407310                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.cruiseportiq   # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/cruiseportiq-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CruisePortIQ - Cruise Planner                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : "Free • Optional Premium Pass $4.99/yr"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : CruisePortIQ is the smart cruise port guide app for travelers. Instantly discover things to do, transport, food & drink, and essential services in every cruise port. Save offline guides and avoid costly ship Wi-Fi.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : CruiseNonstop.com and PPS Digital Marketing Ltd                                
your_link                                 : https://cruisenonstop.com/                     
your_city                                 : Stirling, Scotland, UK                                
email_address                             : feedback@cruisenonstop.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         : cruisenonstop                                          
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Search every cruise port
    description                           : Comprehensive cruise port information with maps, highlights, and insider tips.
    fontawesome_icon_name                 : "search"
    
  - title                                 : Cruise port transport made simple
    description                           : Find shuttles, taxis, buses, trains, and local transport options at your port of call.
    fontawesome_icon_name                 : "bus"

  - title                                 : Top things to do in port
    description                           : Discover excursions, sightseeing highlights, and nearby attractions at each cruise stop.
    fontawesome_icon_name                 : "umbrella-beach"

  - title                                 : Food & drink near the pier
    description                           : Get restaurant and café recommendations in walking distance of your cruise port.
    fontawesome_icon_name                 : "utensils"

  - title                                 : Cruise essentials
    description                           : Banks, ATMs, pharmacies, police stations and more—cruise port essentials at your fingertips.
    fontawesome_icon_name                 : "briefcase-medical"
  
  - title                                 : Plan your cruise itinerary
    description                           : Add your sailing and access port guides directly from your cruise schedule.
    fontawesome_icon_name                 : "calendar-check"

  - title                                 : Favourites for easy access
    description                           : Bookmark places in your cruise port and save them for quick access on arrival. *Premium users can save unlimited places - free users are limited to 5
    fontawesome_icon_name                 : "heart"

  - title                                 : Live port weather
    description                           : Real-time cruise port weather conditions and forecasts to plan your shore days.
    fontawesome_icon_name                 : "cloud-sun"

  - title                                 : Video Cruise Port Guides
    description                           : Watch YouTube cruise vloggers showcase each port—real tips, must-see sights, and what to expect when you dock.
    fontawesome_icon_name                 : "video"

  - title                                 : Premium offline cruise port guides
    description                           : Premium Users can download full cruise port guides for offline use—avoid ship Wi-Fi and roaming costs.
    fontawesome_icon_name                 : "download"



# Theme Settings
topbar_color                              : "#03134F"
topbar_transparency                       : 0.95
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage-santorini.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#03134F"
cover_overlay_transparency                : 0.55

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#008AE0"

app_title_color                           : "#ffffff"
app_price_color                           : "#FED05D"
app_description_color                     : "#ffffff"

feature_title_color                       : "#03134F"
feature_text_color                        : "#444444"

feature_icons_foreground_color            : "#008AE0"
feature_icons_background_color            : "#EBEBEB"

social_icons_foreground_color             : "#03134F"
social_icons_background_color             : "#E6E6E6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
